# Appendix: Data and methodology {-}

The analysis in this report is based on a combination of private and public data sources. The key sources are the following:

- Listing and activity data about Airbnb and Vrbo short-term rental listings gathered by the consulting firm AirDNA. This data includes canonical information about every short-term rental (STR) listing on the Airbnb and Vrbo (including HomeAway) platforms which was active in Prince Edward County between January 1, 2016 and September 30, 2021. The data includes “structural” information such as the listing type (entire home, private room, shared room or hotel room), the number of bedrooms, and the approximate location of the listing. AirDNA collects this information through frequent web scrapes of the public Airbnb and Vrbo websites. The data also includes estimates of listing activity (was the listing reserved, available, or blocked, and what was the nightly price?), which AirDNA produces by applying a machine-learning model to the publicly available calendar information of each listing. We use this data for our core analysis of the STR market, including our counts of active listings, our breakdown of different listing types, our estimates of STR-induced housing loss, and our estimates of listings which are commercial operations.

- Additional data about Airbnb listings collected by UPGo researchers. This includes information to verify activity and location, and listing photographs which were obtained through web scrapes.

- Data from Statistics Canada and the Canada Mortgage and Housing Corporation (CMHC). We use this governmental data to analyze population and dwelling counts, average rents, and rental vacancy rates.

- Data about property sales, graciously provided by the Quinte and District Association of Realtors. This data contains information about every housing sale from January 2016 to September 2021, including date, location, sale price, and time on market, and is used for the analysis of the County's housing market.

- Data about Prince Edward County's private rental market, including location, number of bedrooms, and rent. The data set includes the rent and size of 347 rental units across Prince Edward County for the month of September 2021. This data was provided by Mr. Charles Dowdall, Executive Director of Prince Edward County Affordable Housing Corporation.

- Data about property regulation of short-term accommodations from Prince Edward County. We use this data to conduct the regulation compliance analysis for the purposes of determining the impact and effectiveness of Prince Edward County’s STA by-laws.

_Data cleaning:_ We process the raw STR data we receive from AirDNA through an extensive data cleaning pipeline, the code for which is available at https://github.com/UPGo-McGill/strr.

_Image matching:_ We used our own image recognition algorithm to match listings posted both to Airbnb and Vrbo to combine listings that use the same property. This exercise is conducted to get a more accurate picture of the STR market, and of STR ownership. The algorithm converts the sequence of pixels in an image into a string of numbers representing the average brightness of regions of the image, which serves as a distinctive “signature” of the image, similar to a fingerprint. We compare these signatures to each other using the Pearson correlation coefficient. When the correlation is sufficiently high, we repeat the procedure using separate signatures for the images’ red, blue and green colour channels. All potential matches are then individually verified by human observation. The software package we developed to conduct this image matching is available at https://github.com/UPGo-McGill/matchr.

_FREH modelling:_ We define “frequently rented entire-home listings” as entire-home STR listings which are available for a majority of the year (so 183 days or more in a 365-day period), and which are reserved at least 90 days of that year. This is a consistent and conservative way to estimate listings operated sufficiently often that they are unlikely to be their host’s principal residence. But this indicator is slow to adapt to sudden shocks in STR activity, since it incorporates the past 12 months of a listing’s activity. Given that the COVID-19 pandemic caused STR activity to drop dramatically, we wanted to capture the associated changes at shorter timescales than the one year which our FREH concept allows us to. So we developed a linear regression model which predicts FREH status based on three months of listing activity instead of a full year, and which is calibrated both to routine seasonal variation and to a given market’s specific dynamics. All of the FREH results reported here are the results of this model rather than the raw FREH calculations themselves.

In order to facilitate public understanding and scrutiny of our work, complete methodological details, along with all the code used to produce this analysis, are freely available under an MIT license on the UPGo GitHub page at https://github.com/UPGo-McGill/pec-2021.

\newpage