# References {-}

ACTO. (2021). Tenant protection and rent regulation in Ontario. Advocacy Centre for Tenants Ontario. https://www.acto.ca/production/wp-content/uploads/2019/07/Factsheet_March2021.pdf

Airbnb. (2020). Extenuating circumstances policy and the coronavirus. Airbnb. https://www.airbnb.ca/help/article/2701/extenuating-circumstances-policy-and-the-coronavirus-covid19

Barron, K., Kung, E., & Proserpio, D. (2017). The Effect of Home-Sharing on House Prices and Rents: Evidence from Airbnb. https://papers.ssrn.com/sol3/papers.cfm?abstract_id=3006832 

Boeing, G., & Waddell, P. (2017). New insights into rental housing markets across the United States: Web scraping and analyzing craigslist rental listings. Journal of Planning Education and Research, 37(4), 457-476. https://doi.org/10.1177/0739456X16664789

Celata, F., & Romano, A. (2020). Overtourism and online short-term rental platforms in Italian cities. Journal of Sustainable Tourism. https://www.tandfonline.com/doi/10.1080/09669582.2020.1788568

City of Vancouver. 2020a. Short-term rental business licence. City of Vancouver. Online: https://vancouver.ca/doing-business/short-term-rentals.aspx

CMHC. (21 January 2021). New affordability metric assesses household ability to afford basis goods. Accessed October 2021. https://www.cmhc-schl.gc.ca/en/blog/2020-housing-observer/new-affordability-metric-assesses-household-ability-afford-basic-goods

CMHC. (nd). Methodology for rental market survey. Accessed July 2020.  https://www03.cmhc-schl.gc.ca/hmip-pimh/en/TableMapChart/RmsMethodology

Combs, J., Kerrigan, D., & Wachsmuth, D. (2019 [preprint]). Short-term rentals in Canada: Uneven growth, uneven impacts. Canadian Journal of Urban Research. https://upgo.lab.mcgill.ca/publication/short-term-rentals-in-canada/short-term-rentals-in-canada.pdf 

Countylive. (21 June 2021). Council approves new STA definitions; public mapping to July meeting. Accessed October 2021. https://www.countylive.ca/council-to-review-new-sta-definitions-concerns-about-public-mapping/comment-page-1/

Countylive. (1 September 2020). Council approves freezing all STA licensing; full program review due in January. Accessed October 2021. https://www.countylive.ca/council-to-discuss-freezing-all-sta-licensing-in-the-county/

Deboosere, R., Kerrigan, D. J., Wachsmuth, D., & El-Geneidy, A. (2019). Location, location and professionalization: a multilevel hedonic analysis of Airbnb listing prices and revenue. Regional Studies, Regional Science, 6(1), 143-156. https://doi.org/10.1080/21681376.2019.1592699

deJong, J. (7 October 2021). Summit County finalizes incentive details for its short-term rental conversion program. Summit Daily. Accessed November 2021. https://www.summitdaily.com/news/local/summit-county-finalizes-incentive-details-for-its-short-term-rental-conversion-program/ 

Garcia-López, M. À., Jofre-Monseny, J., Martínez Mazza, R., & Segú, M. (2019). Do short-term rental platforms affect housing markets? Evidence from Airbnb in Barcelona. Retrieved from: https://mpra.ub.uni-muenchen.de/96131/1/MPRA_paper_96131.pdf

Horn, K., & Merante, M. (2017). Is home sharing driving up rents? Evidence from Airbnb in Boston. Journal of Housing Economics, 38, 14-24. https://doi.org/10.1016/j.jhe.2017.08.002

McSheffrey, E. (2020, June 8). The New Reality: As bookings plummet, short-term hosts court long-term tenants during COVID-19. Global News https://globalnews.ca/news/6992034/short-term-rentals-long-term-tenants-coronavirus-covid-19/

Nieuwland, S., & van Melik, R. (2020). Regulating Airbnb: how cities deal with perceived negative externalities of short-term rentals. Current Issues in Tourism, 23(7), 811-825. 10.1080/13683500.2018.1504899

Prince Edward County. (April 2019). Primary market rental vacancy rate. [Report] Municipality of Prince Edward County.

RCLALQ (2020). La flambée des loyers. Enquête sur les prix des logements à louer au Québec. [Report] Regroupement des comités logement et associations de locataires du Québec. https://rclalq.qc.ca/publications/enquete-flambee-des-loyers/ 

The County Foundation. (2018). Vital Signs: Working together to build a place where everyone belongs. Accessed October 2021. https://thecountyfoundation.ca/vital-signs-report-2018-update/

Wachsmuth, D., Bélanger de Blois, M., and St-Hilaire, C. (2021). Short-term rentals in Toronto: Market overview and regulatory impact analysis. [Report]. City of Toronto. Online: https://www.toronto.ca/legdocs/mmis/2021/ph/bgrd/backgroundfile-166717.pdf

Wachsmuth, D., & Weisler, A. (2018). Airbnb and the rent gap: Gentrification through the Sharing Economy. Environmental and Planning A: Economy and Space, 50(6), 1147-1170. https://doi.org/10.1177/0308518X18778038 

Wachsmuth, D., Chaney, D., Kerrigan, D., Shillolo, A., & Basalaev-Binder, R. (2018). The High Cost of
Short-Term Rentals in New York City. https://www.mcgill.ca/newsroom/files/newsroom/channels/attach/
airbnb-report.pdf